version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
    cooldown:
      default-days: 7

  - package-ecosystem: docker
    directories:
      - /archlinux
      - /bazzite
      - /cachyos
    schedule:
      interval: weekly
    groups:
      docker-images:
        patterns:
          - '*'
    cooldown:
      default-days: 7
